language: generic

sudo: false

addons:
  apt:
    sources:
    - cassou-emacs
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot
env:
  - EMACS_VERSION=25.1-rc2
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.0.91 PRETEST=yes
  - EMACS_VERSION=snapshot
before_install:
  # Configure $PATH: Executables are installed to $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  # Download the makefile to emacs-travis.mk
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  # Install Emacs (according to $EMACS_VERSION) and Cask
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
  # Install Texinfo, if you need to build info manuals for your project
  - make -f emacs-travis.mk install_texinfo
  - git clone https://github.com/cask/cask.git "$HOME/.cask"
  - export PATH="$HOME/.cask/bin:$PATH"

install:
  - cask install

script:
  - cask exec ert-runner
  - cask exec emacs -Q -batch -L . -eval "(require 'org-babel-eval-in-repl) (batch-byte-compile)" *.el
  - cask exec ert-runner
  - cask clean-elc

# Local Variables:
# coding: utf-8
# End:
